# Generated by Django 5.1.3 on 2024-11-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textprompt',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userrecording',
            name='text_prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='record.textprompt'),
        ),
    ]
