# Generated by Django 5.1.3 on 2024-11-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_textprompt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecording',
            name='audio_file',
        ),
        migrations.CreateModel(
            name='RecordingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='record.userrecording')),
            ],
        ),
    ]
