# Generated by Django 5.1.3 on 2024-11-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_userrecording_audio_file_recordingfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecording',
            name='text_prompt',
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='record.textprompt')),
            ],
        ),
        migrations.DeleteModel(
            name='RecordingFile',
        ),
        migrations.DeleteModel(
            name='UserRecording',
        ),
    ]
