# Generated by Django 5.1.3 on 2024-11-29 22:16

import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_userrecording_text_prompt_audiofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(upload_to=record.models.audio_file_path),
        ),
    ]
