# Generated by Django 5.1.3 on 2024-11-30 06:23

import django.core.validators
import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_audiofile_audio_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='accent',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('american', 'American English'), ('british', 'British English'), ('australian', 'Australian English'), ('indian', 'Indian English'), ('other', 'Other Accent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('child', 'Child (0-12)'), ('teen', 'Teenager (13-19)'), ('young_adult', 'Young Adult (20-35)'), ('adult', 'Adult (36-55)'), ('senior', 'Senior (55+)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='background_noise_level',
            field=models.FloatField(blank=True, help_text='Estimated background noise level (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='is_ml_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='quality',
            field=models.CharField(blank=True, choices=[('high', 'High Quality'), ('medium', 'Medium Quality'), ('low', 'Low Quality')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='recording_environment',
            field=models.CharField(blank=True, help_text='Recording environment (e.g., quiet room, outdoor, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_clarity_score',
            field=models.FloatField(blank=True, help_text='Speech clarity score (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(upload_to=record.models.audio_file_path, validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3', 'ogg'])]),
        ),
    ]
